%
% Status : main Dynare file
%
% Warning : this file is generated automatically by Dynare
%           from model file (.mod)

tic0 = tic;
% Define global variables.
global M_ options_ oo_ estim_params_ bayestopt_ dataset_ dataset_info estimation_info
options_ = [];
M_.fname = 'IM_peru_ramsey';
M_.dynare_version = '6.5';
oo_.dynare_version = '6.5';
options_.dynare_version = '6.5';
%
% Some global variables initialization
%
global_initialization;
M_.exo_names = cell(2,1);
M_.exo_names_tex = cell(2,1);
M_.exo_names_long = cell(2,1);
M_.exo_names(1) = {'eps_q'};
M_.exo_names_tex(1) = {'eps\_q'};
M_.exo_names_long(1) = {'eps_q'};
M_.exo_names(2) = {'eps_n'};
M_.exo_names_tex(2) = {'eps\_n'};
M_.exo_names_long(2) = {'eps_n'};
M_.endo_names = cell(12,1);
M_.endo_names_tex = cell(12,1);
M_.endo_names_long = cell(12,1);
M_.endo_names(1) = {'z'};
M_.endo_names_tex(1) = {'z'};
M_.endo_names_long(1) = {'z'};
M_.endo_names(2) = {'x'};
M_.endo_names_tex(2) = {'x'};
M_.endo_names_long(2) = {'x'};
M_.endo_names(3) = {'e'};
M_.endo_names_tex(3) = {'e'};
M_.endo_names_long(3) = {'e'};
M_.endo_names(4) = {'b_star'};
M_.endo_names_tex(4) = {'b\_star'};
M_.endo_names_long(4) = {'b_star'};
M_.endo_names(5) = {'q_tilde'};
M_.endo_names_tex(5) = {'q\_tilde'};
M_.endo_names_long(5) = {'q_tilde'};
M_.endo_names(6) = {'n_star'};
M_.endo_names_tex(6) = {'n\_star'};
M_.endo_names_long(6) = {'n_star'};
M_.endo_names(7) = {'f_star'};
M_.endo_names_tex(7) = {'f\_star'};
M_.endo_names_long(7) = {'f_star'};
M_.endo_names(8) = {'MULT_1'};
M_.endo_names_tex(8) = {'MULT\_1'};
M_.endo_names_long(8) = {'MULT_1'};
M_.endo_names(9) = {'MULT_2'};
M_.endo_names_tex(9) = {'MULT\_2'};
M_.endo_names_long(9) = {'MULT_2'};
M_.endo_names(10) = {'MULT_3'};
M_.endo_names_tex(10) = {'MULT\_3'};
M_.endo_names_long(10) = {'MULT_3'};
M_.endo_names(11) = {'MULT_4'};
M_.endo_names_tex(11) = {'MULT\_4'};
M_.endo_names_long(11) = {'MULT_4'};
M_.endo_names(12) = {'MULT_5'};
M_.endo_names_tex(12) = {'MULT\_5'};
M_.endo_names_long(12) = {'MULT_5'};
M_.endo_partitions = struct();
M_.param_names = cell(9,1);
M_.param_names_tex = cell(9,1);
M_.param_names_long = cell(9,1);
M_.param_names(1) = {'beta'};
M_.param_names_tex(1) = {'beta'};
M_.param_names_long(1) = {'beta'};
M_.param_names(2) = {'gamma'};
M_.param_names_tex(2) = {'gamma'};
M_.param_names_long(2) = {'gamma'};
M_.param_names(3) = {'omega_bar'};
M_.param_names_tex(3) = {'omega\_bar'};
M_.param_names_long(3) = {'omega_bar'};
M_.param_names(4) = {'sigma_squared'};
M_.param_names_tex(4) = {'sigma\_squared'};
M_.param_names_long(4) = {'sigma_squared'};
M_.param_names(5) = {'rho_q'};
M_.param_names_tex(5) = {'rho\_q'};
M_.param_names_long(5) = {'rho_q'};
M_.param_names(6) = {'sigma_q'};
M_.param_names_tex(6) = {'sigma\_q'};
M_.param_names_long(6) = {'sigma_q'};
M_.param_names(7) = {'rho_n'};
M_.param_names_tex(7) = {'rho\_n'};
M_.param_names_long(7) = {'rho_n'};
M_.param_names(8) = {'sigma_n'};
M_.param_names_tex(8) = {'sigma\_n'};
M_.param_names_long(8) = {'sigma_n'};
M_.param_names(9) = {'optimal_policy_discount_factor'};
M_.param_names_tex(9) = {'optimal\_policy\_discount\_factor'};
M_.param_names_long(9) = {'optimal_policy_discount_factor'};
M_.param_partitions = struct();
M_.exo_det_nbr = 0;
M_.exo_nbr = 2;
M_.endo_nbr = 12;
M_.param_nbr = 9;
M_.orig_endo_nbr = 7;
M_.aux_vars(1).endo_index = 8;
M_.aux_vars(1).type = 6;
M_.aux_vars(1).eq_nbr = 1;
M_.aux_vars(2).endo_index = 9;
M_.aux_vars(2).type = 6;
M_.aux_vars(2).eq_nbr = 2;
M_.aux_vars(3).endo_index = 10;
M_.aux_vars(3).type = 6;
M_.aux_vars(3).eq_nbr = 3;
M_.aux_vars(4).endo_index = 11;
M_.aux_vars(4).type = 6;
M_.aux_vars(4).eq_nbr = 4;
M_.aux_vars(5).endo_index = 12;
M_.aux_vars(5).type = 6;
M_.aux_vars(5).eq_nbr = 5;
M_.Sigma_e = zeros(2, 2);
M_.Correlation_matrix = eye(2, 2);
M_.H = 0;
M_.Correlation_matrix_ME = 1;
M_.sigma_e_is_diagonal = true;
M_.det_shocks = [];
M_.surprise_shocks = [];
M_.learnt_shocks = [];
M_.learnt_endval = [];
M_.heteroskedastic_shocks.Qvalue_orig = [];
M_.heteroskedastic_shocks.Qscale_orig = [];
M_.matched_irfs = {};
M_.matched_irfs_weights = {};
options_.linear = false;
options_.block = false;
options_.bytecode = false;
options_.use_dll = false;
options_.ramsey_policy = true;
options_.discretionary_policy = false;
M_.eq_nbr = 12;
M_.ramsey_orig_eq_nbr = 5;
M_.ramsey_orig_endo_nbr = 7;
M_.set_auxiliary_variables = exist(['./+' M_.fname '/set_auxiliary_variables.m'], 'file') == 2;
M_.epilogue_names = {};
M_.epilogue_var_list_ = {};
M_.orig_maximum_endo_lag = 1;
M_.orig_maximum_endo_lead = 1;
M_.orig_maximum_exo_lag = 0;
M_.orig_maximum_exo_lead = 0;
M_.orig_maximum_exo_det_lag = 0;
M_.orig_maximum_exo_det_lead = 0;
M_.orig_maximum_lag = 1;
M_.orig_maximum_lead = 1;
M_.orig_maximum_lag_with_diffs_expanded = 1;
M_.lead_lag_incidence = [
 0 5 17;
 0 6 0;
 0 7 0;
 1 8 0;
 2 9 0;
 3 10 0;
 0 11 0;
 0 12 0;
 0 13 18;
 4 14 0;
 0 15 19;
 0 16 20;]';
M_.nstatic = 4;
M_.nfwrd   = 4;
M_.npred   = 4;
M_.nboth   = 0;
M_.nsfwrd   = 4;
M_.nspred   = 4;
M_.ndynamic   = 8;
M_.dynamic_tmp_nbr = [1; 0; 0; 0; ];
M_.equations_tags = {
  8 , 'name' , 'e' ;
  9 , 'name' , '2' ;
  10 , 'name' , 'z' ;
  11 , 'name' , 'q_tilde' ;
  12 , 'name' , 'n_star' ;
};
M_.mapping.z.eqidx = [1 8 9 10 ];
M_.mapping.x.eqidx = [2 8 ];
M_.mapping.e.eqidx = [8 ];
M_.mapping.b_star.eqidx = [9 10 ];
M_.mapping.q_tilde.eqidx = [8 11 ];
M_.mapping.n_star.eqidx = [10 12 ];
M_.mapping.f_star.eqidx = [10 ];
M_.mapping.eps_q.eqidx = [11 ];
M_.mapping.eps_n.eqidx = [12 ];
M_.mapping.MULT_1.eqidx = [1 2 3 5 ];
M_.mapping.MULT_2.eqidx = [1 4 ];
M_.mapping.MULT_3.eqidx = [1 4 6 7 ];
M_.mapping.MULT_4.eqidx = [5 ];
M_.mapping.MULT_5.eqidx = [6 ];
M_.static_and_dynamic_models_differ = false;
M_.has_external_function = false;
M_.block_structure.time_recursive = false;
M_.block_structure.block(1).Simulation_Type = 1;
M_.block_structure.block(1).endo_nbr = 1;
M_.block_structure.block(1).mfs = 1;
M_.block_structure.block(1).equation = [ 3];
M_.block_structure.block(1).variable = [ 8];
M_.block_structure.block(1).is_linear = true;
M_.block_structure.block(1).NNZDerivatives = 1;
M_.block_structure.block(1).bytecode_jacob_cols_to_sparse = [2 ];
M_.block_structure.block(2).Simulation_Type = 4;
M_.block_structure.block(2).endo_nbr = 1;
M_.block_structure.block(2).mfs = 1;
M_.block_structure.block(2).equation = [ 5];
M_.block_structure.block(2).variable = [ 11];
M_.block_structure.block(2).is_linear = true;
M_.block_structure.block(2).NNZDerivatives = 2;
M_.block_structure.block(2).bytecode_jacob_cols_to_sparse = [1 0 ];
M_.block_structure.block(3).Simulation_Type = 3;
M_.block_structure.block(3).endo_nbr = 1;
M_.block_structure.block(3).mfs = 1;
M_.block_structure.block(3).equation = [ 7];
M_.block_structure.block(3).variable = [ 10];
M_.block_structure.block(3).is_linear = true;
M_.block_structure.block(3).NNZDerivatives = 1;
M_.block_structure.block(3).bytecode_jacob_cols_to_sparse = [1 ];
M_.block_structure.block(4).Simulation_Type = 3;
M_.block_structure.block(4).endo_nbr = 1;
M_.block_structure.block(4).mfs = 1;
M_.block_structure.block(4).equation = [ 11];
M_.block_structure.block(4).variable = [ 5];
M_.block_structure.block(4).is_linear = true;
M_.block_structure.block(4).NNZDerivatives = 2;
M_.block_structure.block(4).bytecode_jacob_cols_to_sparse = [0 1 ];
M_.block_structure.block(5).Simulation_Type = 3;
M_.block_structure.block(5).endo_nbr = 1;
M_.block_structure.block(5).mfs = 1;
M_.block_structure.block(5).equation = [ 12];
M_.block_structure.block(5).variable = [ 6];
M_.block_structure.block(5).is_linear = true;
M_.block_structure.block(5).NNZDerivatives = 2;
M_.block_structure.block(5).bytecode_jacob_cols_to_sparse = [0 1 ];
M_.block_structure.block(6).Simulation_Type = 4;
M_.block_structure.block(6).endo_nbr = 1;
M_.block_structure.block(6).mfs = 1;
M_.block_structure.block(6).equation = [ 6];
M_.block_structure.block(6).variable = [ 12];
M_.block_structure.block(6).is_linear = true;
M_.block_structure.block(6).NNZDerivatives = 2;
M_.block_structure.block(6).bytecode_jacob_cols_to_sparse = [1 0 ];
M_.block_structure.block(7).Simulation_Type = 4;
M_.block_structure.block(7).endo_nbr = 1;
M_.block_structure.block(7).mfs = 1;
M_.block_structure.block(7).equation = [ 4];
M_.block_structure.block(7).variable = [ 9];
M_.block_structure.block(7).is_linear = true;
M_.block_structure.block(7).NNZDerivatives = 2;
M_.block_structure.block(7).bytecode_jacob_cols_to_sparse = [1 0 ];
M_.block_structure.block(8).Simulation_Type = 3;
M_.block_structure.block(8).endo_nbr = 1;
M_.block_structure.block(8).mfs = 1;
M_.block_structure.block(8).equation = [ 2];
M_.block_structure.block(8).variable = [ 2];
M_.block_structure.block(8).is_linear = true;
M_.block_structure.block(8).NNZDerivatives = 1;
M_.block_structure.block(8).bytecode_jacob_cols_to_sparse = [1 ];
M_.block_structure.block(9).Simulation_Type = 3;
M_.block_structure.block(9).endo_nbr = 1;
M_.block_structure.block(9).mfs = 1;
M_.block_structure.block(9).equation = [ 1];
M_.block_structure.block(9).variable = [ 1];
M_.block_structure.block(9).is_linear = true;
M_.block_structure.block(9).NNZDerivatives = 1;
M_.block_structure.block(9).bytecode_jacob_cols_to_sparse = [1 ];
M_.block_structure.block(10).Simulation_Type = 3;
M_.block_structure.block(10).endo_nbr = 1;
M_.block_structure.block(10).mfs = 1;
M_.block_structure.block(10).equation = [ 8];
M_.block_structure.block(10).variable = [ 3];
M_.block_structure.block(10).is_linear = true;
M_.block_structure.block(10).NNZDerivatives = 1;
M_.block_structure.block(10).bytecode_jacob_cols_to_sparse = [1 ];
M_.block_structure.block(11).Simulation_Type = 3;
M_.block_structure.block(11).endo_nbr = 1;
M_.block_structure.block(11).mfs = 1;
M_.block_structure.block(11).equation = [ 9];
M_.block_structure.block(11).variable = [ 4];
M_.block_structure.block(11).is_linear = true;
M_.block_structure.block(11).NNZDerivatives = 2;
M_.block_structure.block(11).bytecode_jacob_cols_to_sparse = [0 1 ];
M_.block_structure.block(12).Simulation_Type = 3;
M_.block_structure.block(12).endo_nbr = 1;
M_.block_structure.block(12).mfs = 1;
M_.block_structure.block(12).equation = [ 10];
M_.block_structure.block(12).variable = [ 7];
M_.block_structure.block(12).is_linear = true;
M_.block_structure.block(12).NNZDerivatives = 1;
M_.block_structure.block(12).bytecode_jacob_cols_to_sparse = [1 ];
M_.block_structure.block(1).g1_sparse_rowval = int32([]);
M_.block_structure.block(1).g1_sparse_colval = int32([]);
M_.block_structure.block(1).g1_sparse_colptr = int32([]);
M_.block_structure.block(2).g1_sparse_rowval = int32([1 ]);
M_.block_structure.block(2).g1_sparse_colval = int32([1 ]);
M_.block_structure.block(2).g1_sparse_colptr = int32([1 2 ]);
M_.block_structure.block(3).g1_sparse_rowval = int32([1 ]);
M_.block_structure.block(3).g1_sparse_colval = int32([1 ]);
M_.block_structure.block(3).g1_sparse_colptr = int32([1 2 ]);
M_.block_structure.block(4).g1_sparse_rowval = int32([1 ]);
M_.block_structure.block(4).g1_sparse_colval = int32([1 ]);
M_.block_structure.block(4).g1_sparse_colptr = int32([1 2 ]);
M_.block_structure.block(5).g1_sparse_rowval = int32([1 ]);
M_.block_structure.block(5).g1_sparse_colval = int32([1 ]);
M_.block_structure.block(5).g1_sparse_colptr = int32([1 2 ]);
M_.block_structure.block(6).g1_sparse_rowval = int32([1 ]);
M_.block_structure.block(6).g1_sparse_colval = int32([1 ]);
M_.block_structure.block(6).g1_sparse_colptr = int32([1 2 ]);
M_.block_structure.block(7).g1_sparse_rowval = int32([1 ]);
M_.block_structure.block(7).g1_sparse_colval = int32([1 ]);
M_.block_structure.block(7).g1_sparse_colptr = int32([1 2 ]);
M_.block_structure.block(8).g1_sparse_rowval = int32([1 ]);
M_.block_structure.block(8).g1_sparse_colval = int32([1 ]);
M_.block_structure.block(8).g1_sparse_colptr = int32([1 2 ]);
M_.block_structure.block(9).g1_sparse_rowval = int32([1 ]);
M_.block_structure.block(9).g1_sparse_colval = int32([1 ]);
M_.block_structure.block(9).g1_sparse_colptr = int32([1 2 ]);
M_.block_structure.block(10).g1_sparse_rowval = int32([1 ]);
M_.block_structure.block(10).g1_sparse_colval = int32([1 ]);
M_.block_structure.block(10).g1_sparse_colptr = int32([1 2 ]);
M_.block_structure.block(11).g1_sparse_rowval = int32([1 ]);
M_.block_structure.block(11).g1_sparse_colval = int32([1 ]);
M_.block_structure.block(11).g1_sparse_colptr = int32([1 2 ]);
M_.block_structure.block(12).g1_sparse_rowval = int32([1 ]);
M_.block_structure.block(12).g1_sparse_colval = int32([1 ]);
M_.block_structure.block(12).g1_sparse_colptr = int32([1 2 ]);
M_.block_structure.variable_reordered = [ 8 11 10 5 6 12 9 2 1 3 4 7];
M_.block_structure.equation_reordered = [ 3 5 7 11 12 6 4 2 1 8 9 10];
M_.block_structure.incidence(1).lead_lag = -1;
M_.block_structure.incidence(1).sparse_IM = [
 1 10;
 9 4;
 11 5;
 12 6;
];
M_.block_structure.incidence(2).lead_lag = 0;
M_.block_structure.incidence(2).sparse_IM = [
 1 1;
 1 8;
 1 9;
 1 10;
 2 2;
 2 8;
 3 8;
 4 9;
 4 10;
 5 8;
 5 11;
 6 10;
 6 12;
 7 10;
 8 1;
 8 2;
 8 3;
 8 5;
 9 1;
 9 4;
 10 1;
 10 4;
 10 6;
 10 7;
 11 5;
 12 6;
];
M_.block_structure.incidence(3).lead_lag = 1;
M_.block_structure.incidence(3).sparse_IM = [
 4 9;
 5 11;
 6 12;
 10 1;
];
M_.block_structure.dyn_tmp_nbr = 0;
M_.state_var = [10 5 6 4 ];
M_.maximum_lag = 1;
M_.maximum_lead = 1;
M_.maximum_endo_lag = 1;
M_.maximum_endo_lead = 1;
oo_.steady_state = zeros(12, 1);
M_.maximum_exo_lag = 0;
M_.maximum_exo_lead = 0;
oo_.exo_steady_state = zeros(2, 1);
M_.params = NaN(9, 1);
M_.endo_trends = struct('deflator', cell(12, 1), 'log_deflator', cell(12, 1), 'growth_factor', cell(12, 1), 'log_growth_factor', cell(12, 1));
M_.NNZDerivatives = [36; -1; -1; ];
M_.dynamic_g1_sparse_rowval = int32([9 11 12 1 1 8 9 10 2 8 8 9 10 8 11 10 12 10 1 2 3 5 1 4 1 4 6 7 5 6 10 4 5 6 11 12 ]);
M_.dynamic_g1_sparse_colval = int32([4 5 6 10 13 13 13 13 14 14 15 16 16 17 17 18 18 19 20 20 20 20 21 21 22 22 22 22 23 24 25 33 35 36 37 38 ]);
M_.dynamic_g1_sparse_colptr = int32([1 1 1 1 2 3 4 4 4 4 5 5 5 9 11 12 14 16 18 19 23 25 29 30 31 32 32 32 32 32 32 32 32 33 33 34 35 36 37 ]);
M_.lhs = {
'MULT_1+MULT_2-MULT_3+optimal_policy_discount_factor^(-1)*MULT_3(-1)-gamma*2*z'; 
'(-MULT_1)-(1-gamma)*2*x'; 
'MULT_1'; 
'omega_bar*sigma_squared*MULT_3+beta*MULT_2+optimal_policy_discount_factor*(-MULT_2(1))'; 
'MULT_4+optimal_policy_discount_factor*MULT_4(1)*(-rho_q)-MULT_1'; 
'MULT_5+MULT_3*(-(omega_bar*sigma_squared))+optimal_policy_discount_factor*MULT_5(1)*(-rho_n)'; 
'MULT_3*(-(omega_bar*sigma_squared))'; 
'e-(q_tilde+x-z)'; 
'beta*b_star-(b_star(-1)-z)'; 
'z(1)-(z+omega_bar*sigma_squared*(n_star+f_star-b_star))'; 
'q_tilde-(rho_q*q_tilde(-1)+eps_q)'; 
'n_star-(rho_n*n_star(-1)+eps_n)'; 
};
M_.static_tmp_nbr = [1; 0; 0; 0; ];
M_.block_structure_stat.block(1).Simulation_Type = 1;
M_.block_structure_stat.block(1).endo_nbr = 1;
M_.block_structure_stat.block(1).mfs = 1;
M_.block_structure_stat.block(1).equation = [ 3];
M_.block_structure_stat.block(1).variable = [ 8];
M_.block_structure_stat.block(2).Simulation_Type = 3;
M_.block_structure_stat.block(2).endo_nbr = 1;
M_.block_structure_stat.block(2).mfs = 1;
M_.block_structure_stat.block(2).equation = [ 5];
M_.block_structure_stat.block(2).variable = [ 11];
M_.block_structure_stat.block(3).Simulation_Type = 3;
M_.block_structure_stat.block(3).endo_nbr = 1;
M_.block_structure_stat.block(3).mfs = 1;
M_.block_structure_stat.block(3).equation = [ 7];
M_.block_structure_stat.block(3).variable = [ 10];
M_.block_structure_stat.block(4).Simulation_Type = 3;
M_.block_structure_stat.block(4).endo_nbr = 1;
M_.block_structure_stat.block(4).mfs = 1;
M_.block_structure_stat.block(4).equation = [ 11];
M_.block_structure_stat.block(4).variable = [ 5];
M_.block_structure_stat.block(5).Simulation_Type = 3;
M_.block_structure_stat.block(5).endo_nbr = 1;
M_.block_structure_stat.block(5).mfs = 1;
M_.block_structure_stat.block(5).equation = [ 12];
M_.block_structure_stat.block(5).variable = [ 6];
M_.block_structure_stat.block(6).Simulation_Type = 3;
M_.block_structure_stat.block(6).endo_nbr = 1;
M_.block_structure_stat.block(6).mfs = 1;
M_.block_structure_stat.block(6).equation = [ 6];
M_.block_structure_stat.block(6).variable = [ 12];
M_.block_structure_stat.block(7).Simulation_Type = 3;
M_.block_structure_stat.block(7).endo_nbr = 1;
M_.block_structure_stat.block(7).mfs = 1;
M_.block_structure_stat.block(7).equation = [ 4];
M_.block_structure_stat.block(7).variable = [ 9];
M_.block_structure_stat.block(8).Simulation_Type = 3;
M_.block_structure_stat.block(8).endo_nbr = 1;
M_.block_structure_stat.block(8).mfs = 1;
M_.block_structure_stat.block(8).equation = [ 2];
M_.block_structure_stat.block(8).variable = [ 2];
M_.block_structure_stat.block(9).Simulation_Type = 3;
M_.block_structure_stat.block(9).endo_nbr = 1;
M_.block_structure_stat.block(9).mfs = 1;
M_.block_structure_stat.block(9).equation = [ 1];
M_.block_structure_stat.block(9).variable = [ 1];
M_.block_structure_stat.block(10).Simulation_Type = 3;
M_.block_structure_stat.block(10).endo_nbr = 1;
M_.block_structure_stat.block(10).mfs = 1;
M_.block_structure_stat.block(10).equation = [ 8];
M_.block_structure_stat.block(10).variable = [ 3];
M_.block_structure_stat.block(11).Simulation_Type = 3;
M_.block_structure_stat.block(11).endo_nbr = 1;
M_.block_structure_stat.block(11).mfs = 1;
M_.block_structure_stat.block(11).equation = [ 9];
M_.block_structure_stat.block(11).variable = [ 4];
M_.block_structure_stat.block(12).Simulation_Type = 3;
M_.block_structure_stat.block(12).endo_nbr = 1;
M_.block_structure_stat.block(12).mfs = 1;
M_.block_structure_stat.block(12).equation = [ 10];
M_.block_structure_stat.block(12).variable = [ 7];
M_.block_structure_stat.variable_reordered = [ 8 11 10 5 6 12 9 2 1 3 4 7];
M_.block_structure_stat.equation_reordered = [ 3 5 7 11 12 6 4 2 1 8 9 10];
M_.block_structure_stat.incidence.sparse_IM = [
 1 1;
 1 8;
 1 9;
 1 10;
 2 2;
 2 8;
 3 8;
 4 9;
 4 10;
 5 8;
 5 11;
 6 10;
 6 12;
 7 10;
 8 1;
 8 2;
 8 3;
 8 5;
 9 1;
 9 4;
 10 4;
 10 6;
 10 7;
 11 5;
 12 6;
];
M_.block_structure_stat.tmp_nbr = 0;
M_.block_structure_stat.block(1).g1_sparse_rowval = int32([]);
M_.block_structure_stat.block(1).g1_sparse_colval = int32([]);
M_.block_structure_stat.block(1).g1_sparse_colptr = int32([]);
M_.block_structure_stat.block(2).g1_sparse_rowval = int32([1 ]);
M_.block_structure_stat.block(2).g1_sparse_colval = int32([1 ]);
M_.block_structure_stat.block(2).g1_sparse_colptr = int32([1 2 ]);
M_.block_structure_stat.block(3).g1_sparse_rowval = int32([1 ]);
M_.block_structure_stat.block(3).g1_sparse_colval = int32([1 ]);
M_.block_structure_stat.block(3).g1_sparse_colptr = int32([1 2 ]);
M_.block_structure_stat.block(4).g1_sparse_rowval = int32([1 ]);
M_.block_structure_stat.block(4).g1_sparse_colval = int32([1 ]);
M_.block_structure_stat.block(4).g1_sparse_colptr = int32([1 2 ]);
M_.block_structure_stat.block(5).g1_sparse_rowval = int32([1 ]);
M_.block_structure_stat.block(5).g1_sparse_colval = int32([1 ]);
M_.block_structure_stat.block(5).g1_sparse_colptr = int32([1 2 ]);
M_.block_structure_stat.block(6).g1_sparse_rowval = int32([1 ]);
M_.block_structure_stat.block(6).g1_sparse_colval = int32([1 ]);
M_.block_structure_stat.block(6).g1_sparse_colptr = int32([1 2 ]);
M_.block_structure_stat.block(7).g1_sparse_rowval = int32([1 ]);
M_.block_structure_stat.block(7).g1_sparse_colval = int32([1 ]);
M_.block_structure_stat.block(7).g1_sparse_colptr = int32([1 2 ]);
M_.block_structure_stat.block(8).g1_sparse_rowval = int32([1 ]);
M_.block_structure_stat.block(8).g1_sparse_colval = int32([1 ]);
M_.block_structure_stat.block(8).g1_sparse_colptr = int32([1 2 ]);
M_.block_structure_stat.block(9).g1_sparse_rowval = int32([1 ]);
M_.block_structure_stat.block(9).g1_sparse_colval = int32([1 ]);
M_.block_structure_stat.block(9).g1_sparse_colptr = int32([1 2 ]);
M_.block_structure_stat.block(10).g1_sparse_rowval = int32([1 ]);
M_.block_structure_stat.block(10).g1_sparse_colval = int32([1 ]);
M_.block_structure_stat.block(10).g1_sparse_colptr = int32([1 2 ]);
M_.block_structure_stat.block(11).g1_sparse_rowval = int32([1 ]);
M_.block_structure_stat.block(11).g1_sparse_colval = int32([1 ]);
M_.block_structure_stat.block(11).g1_sparse_colptr = int32([1 2 ]);
M_.block_structure_stat.block(12).g1_sparse_rowval = int32([1 ]);
M_.block_structure_stat.block(12).g1_sparse_colval = int32([1 ]);
M_.block_structure_stat.block(12).g1_sparse_colptr = int32([1 2 ]);
M_.static_g1_sparse_rowval = int32([1 8 9 2 8 8 9 10 8 11 10 12 10 1 2 3 5 1 4 1 4 6 7 5 6 ]);
M_.static_g1_sparse_colval = int32([1 1 1 2 2 3 4 4 5 5 6 6 7 8 8 8 8 9 9 10 10 10 10 11 12 ]);
M_.static_g1_sparse_colptr = int32([1 4 6 7 9 11 13 14 18 20 24 25 26 ]);
M_.ramsey_multipliers_static_g1_sparse_rowval = int32([1 2 3 5 1 4 1 4 6 7 5 6 ]);
M_.ramsey_multipliers_static_g1_sparse_colval = int32([1 1 1 1 2 2 3 3 3 3 4 5 ]);
M_.ramsey_multipliers_static_g1_sparse_colptr = int32([1 5 7 11 12 13 ]);
M_.params(1) = 0.995;
beta = M_.params(1);
M_.params(2) = 0.27;
gamma = M_.params(2);
M_.params(3) = 0.5;
omega_bar = M_.params(3);
M_.params(4) = 0.001;
sigma_squared = M_.params(4);
M_.params(5) = 0.85;
rho_q = M_.params(5);
M_.params(6) = 0.03;
sigma_q = M_.params(6);
M_.params(7) = 0.70;
rho_n = M_.params(7);
M_.params(8) = 0.01;
sigma_n = M_.params(8);
M_.params(9) = 0.995;
optimal_policy_discount_factor = M_.params(9);
options_.instruments = {'f_star';'x'};
M_.NNZDerivatives_objective = [2;2;0;];
M_.objective_tmp_nbr = [0; 0; 0; 0; ];
%
% INITVAL instructions
%
options_.initval_file = false;
oo_.steady_state(1) = 0;
oo_.steady_state(2) = 0;
oo_.steady_state(3) = 0;
oo_.steady_state(4) = 0;
oo_.steady_state(5) = 0;
oo_.steady_state(6) = 0;
oo_.steady_state(7) = 0;
if M_.exo_nbr > 0
	oo_.exo_simul = ones(M_.maximum_lag,1)*oo_.exo_steady_state';
end
if M_.exo_det_nbr > 0
	oo_.exo_det_simul = ones(M_.maximum_lag,1)*oo_.exo_det_steady_state';
end
options_.solve_algo = 4;
steady;
%
% SHOCKS instructions
%
M_.exo_det_length = 0;
M_.Sigma_e(1, 1) = M_.params(6)^2;
M_.Sigma_e(2, 2) = M_.params(8)^2;
options_.irf = 40;
options_.nograph = true;
options_.order = 1;
var_list_ = {};
[info, oo_, options_, M_] = stoch_simul(M_, options_, oo_, var_list_);
oo_.planner_objective_value = evaluate_planner_objective(M_, options_, oo_);


oo_.time = toc(tic0);
disp(['Total computing time : ' dynsec2hms(oo_.time) ]);
if ~exist([M_.dname filesep 'Output'],'dir')
    mkdir(M_.dname,'Output');
end
save([M_.dname filesep 'Output' filesep 'IM_peru_ramsey_results.mat'], 'oo_', 'M_', 'options_');
if exist('estim_params_', 'var') == 1
  save([M_.dname filesep 'Output' filesep 'IM_peru_ramsey_results.mat'], 'estim_params_', '-append');
end
if exist('bayestopt_', 'var') == 1
  save([M_.dname filesep 'Output' filesep 'IM_peru_ramsey_results.mat'], 'bayestopt_', '-append');
end
if exist('dataset_', 'var') == 1
  save([M_.dname filesep 'Output' filesep 'IM_peru_ramsey_results.mat'], 'dataset_', '-append');
end
if exist('estimation_info', 'var') == 1
  save([M_.dname filesep 'Output' filesep 'IM_peru_ramsey_results.mat'], 'estimation_info', '-append');
end
if exist('dataset_info', 'var') == 1
  save([M_.dname filesep 'Output' filesep 'IM_peru_ramsey_results.mat'], 'dataset_info', '-append');
end
if exist('oo_recursive_', 'var') == 1
  save([M_.dname filesep 'Output' filesep 'IM_peru_ramsey_results.mat'], 'oo_recursive_', '-append');
end
if exist('options_mom_', 'var') == 1
  save([M_.dname filesep 'Output' filesep 'IM_peru_ramsey_results.mat'], 'options_mom_', '-append');
end
if ~isempty(lastwarn)
  disp('Note: warning(s) encountered in MATLAB/Octave code')
end
